/*
 * Newrow 0.1.0
 * Blackjack
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: aaron.s.hawley@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ninthfloor.bj21.api.gson;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.ninthfloor.bj21.api.gson.Hand;

/**
 * Hands
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-12-02T12:31:35.168-05:00[America/New_York]")
public class Hands {
  public static final String SERIALIZED_NAME_BET = "bet";
  @SerializedName(SERIALIZED_NAME_BET)
  private Long bet;

  public static final String SERIALIZED_NAME_HANDS = "hands";
  @SerializedName(SERIALIZED_NAME_HANDS)
  private List<Hand> hands = new ArrayList<>();


  public Hands bet(Long bet) {
    
    this.bet = bet;
    return this;
  }

   /**
   * Initial player bet
   * @return bet
  **/
  @ApiModelProperty(required = true, value = "Initial player bet")

  public Long getBet() {
    return bet;
  }


  public void setBet(Long bet) {
    this.bet = bet;
  }


  public Hands hands(List<Hand> hands) {
    
    this.hands = hands;
    return this;
  }

  public Hands addHandsItem(Hand handsItem) {
    this.hands.add(handsItem);
    return this;
  }

   /**
   * Hands of player
   * @return hands
  **/
  @ApiModelProperty(required = true, value = "Hands of player")

  public List<Hand> getHands() {
    return hands;
  }


  public void setHands(List<Hand> hands) {
    this.hands = hands;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Hands hands = (Hands) o;
    return Objects.equals(this.bet, hands.bet) &&
        Objects.equals(this.hands, hands.hands);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bet, hands);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Hands {\n");
    sb.append("    bet: ").append(toIndentedString(bet)).append("\n");
    sb.append("    hands: ").append(toIndentedString(hands)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

