/*
 * Newrow 1.3.1
 * Newrow API
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: help@newrow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ninthfloor.bj21.api.gson;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * UserDeletedData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-30T02:06:05.241-05:00[America/New_York]")
public class UserDeletedData {
  public static final String SERIALIZED_NAME_DELETED_USER_ROOMS = "deleted_user_rooms";
  @SerializedName(SERIALIZED_NAME_DELETED_USER_ROOMS)
  private Long deletedUserRooms;

  public static final String SERIALIZED_NAME_COMPANY_USER_DELETED = "company_user_deleted";
  @SerializedName(SERIALIZED_NAME_COMPANY_USER_DELETED)
  private Long companyUserDeleted;


  public UserDeletedData deletedUserRooms(Long deletedUserRooms) {
    
    this.deletedUserRooms = deletedUserRooms;
    return this;
  }

   /**
   * Get deletedUserRooms
   * @return deletedUserRooms
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getDeletedUserRooms() {
    return deletedUserRooms;
  }


  public void setDeletedUserRooms(Long deletedUserRooms) {
    this.deletedUserRooms = deletedUserRooms;
  }


  public UserDeletedData companyUserDeleted(Long companyUserDeleted) {
    
    this.companyUserDeleted = companyUserDeleted;
    return this;
  }

   /**
   * Get companyUserDeleted
   * @return companyUserDeleted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getCompanyUserDeleted() {
    return companyUserDeleted;
  }


  public void setCompanyUserDeleted(Long companyUserDeleted) {
    this.companyUserDeleted = companyUserDeleted;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserDeletedData userDeletedData = (UserDeletedData) o;
    return Objects.equals(this.deletedUserRooms, userDeletedData.deletedUserRooms) &&
        Objects.equals(this.companyUserDeleted, userDeletedData.companyUserDeleted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deletedUserRooms, companyUserDeleted);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserDeletedData {\n");
    sb.append("    deletedUserRooms: ").append(toIndentedString(deletedUserRooms)).append("\n");
    sb.append("    companyUserDeleted: ").append(toIndentedString(companyUserDeleted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

