service: aahawley-testapp

frameworkVersion: ">=1.8.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  environment:
    TABLES_TABLE_NAME:
      Ref: tablesTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        "Fn::Join":
          - ""
          -
            - "arn:aws:dynamodb:"
            - Ref: "AWS::Region"
            - ":"
            - Ref: "AWS::AccountId"
            - ":table/"
            - Ref: tablesTable

package:
  artifact: bj21-lambda/target/bj21-lambda-0.1.0-SNAPSHOT-bin.jar

functions:
  addTable:
    handler: org.ninthfloor.bj21.lambda.v0.AddTable
    events:
      - http:
          path: /v0/tables
          method: post
  getTableById:
    handler: org.ninthfloor.bj21.lambda.v0.GetTableById
    events:
      - http:
          path: /v0/tables/{tableId}
          method: get
          parameters:
            paths:
              tableId: true
  updateTable:
    handler: org.ninthfloor.bj21.lambda.v0.UpdateTable
    events:
      - http:
          path: /v0/tables/{tableId}
          method: put
          parameters:
            paths:
              tableId: true
  deleteTable:
    handler: org.ninthfloor.bj21.lambda.v0.DeleteTable
    events:
      - http:
          path: /v0/tables/{tableId}
          method: delete
          parameters:
            paths:
              tableId: true
  addDealer:
    # handler: org.ninthfloor.bj21.lambda.v0.AddDealer
    handler: org.ninthfloor.bj21.lambda.v0.Dummy
    events:
      - http:
          path: /v0/tables/{tableId}/dealer
          method: post
          integration: mock
          request:
            template:
              application/json: '{"statusCode": 501}'
          response:
            template: $input.path('$')
            statusCodes:
              201:
                pattern: ''
  findDealerByTable:
    # handler: org.ninthfloor.bj21.lambda.v0.FindDealerByTable
    handler: org.ninthfloor.bj21.lambda.v0.Dummy
    events:
      - http:
          path: /v0/tables/{tableId}/dealer
          method: get
          parameters:
            paths:
              tableId: true
          integration: mock
          request:
            template:
              application/json: '{"statusCode": 501"}'
          response:
            template: $input.path('$')
            statusCodes:
              501:
                pattern: ''
  updateDealer:
    # handler: org.ninthfloor.bj21.lambda.v0.UpdateDealer
    handler: org.ninthfloor.bj21.lambda.v0.Dummy
    events:
      - http:
          path: /v0/tables/{tableId}/dealer
          method: put
          parameters:
            paths:
              tableId: true
          integration: mock
          request:
            template:
              application/json: '{"statusCode": 501"}'
          response:
            template: $input.path('$')
            statusCodes:
              501:
                pattern: ''
  deleteDealer:
    # handler: org.ninthfloor.bj21.lambda.v0.DeleteDealer
    handler: org.ninthfloor.bj21.lambda.v0.Dummy
    events:
      - http:
          path: /v0/tables/{tableId}/dealer
          method: delete
          parameters:
            paths:
              tableId: true
          integration: mock
          request:
            template:
              application/json: '{"statusCode": 501}'
          response:
            template: $input.path('$')
            statusCodes:
              501:
                pattern: ''

resources:
  Resources:
    tablesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
          - AttributeName: id
            AttributeType: N
        KeySchema:

          - AttributeName: key
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
