service: aahawley-testapp

frameworkVersion: ">=1.8.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  environment:
    TABLES_TABLE_NAME:
      Ref: tablesTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        "Fn::Join":
          - ""
          -
            - "arn:aws:dynamodb:"
            - Ref: "AWS::Region"
            - ":"
            - Ref: "AWS::AccountId"
            - ":table/"
            - Ref: tablesTable

package:
  artifact: bj21-lambda/target/bj21-lambda-0.1.0-SNAPSHOT-bin.jar

functions:
  addTable:
    handler: org.ninthfloor.bj21.lambda.v0.AddTable
    events:
      - http:
          path: /v0/tables
          method: post

resources:
  Resources:
    tablesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
          - AttributeName: id
            AttributeType: N
        KeySchema:

          - AttributeName: key
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
