service: aahawley-testapp

frameworkVersion: ">=1.8.0 <2.0.0"

provider:
  name: aws
  runtime: java8

package:
  artifact: bj21-lambda/target/bj21-lambda-0.1.0-SNAPSHOT-bin.jar

functions:
  addTable:
    handler: org.ninthfloor.bj21.lambda.v0.AddTable
    events:
      - http:
          path: /v0/tables
          method: post
