/*
 * Newrow 0.1.0
 * Blackjack
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: aaron.s.hawley@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ninthfloor.bj21.gson;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.ninthfloor.bj21.gson.Hand;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Hands
 */
public class HandsTest {
    private final Hands model = new Hands();

    /**
     * Model tests for Hands
     */
    @Test
    public void testHands() {
        // TODO: test Hands
    }

    /**
     * Test the property 'bet'
     */
    @Test
    public void betTest() {
        // TODO: test bet
    }

    /**
     * Test the property 'hands'
     */
    @Test
    public void handsTest() {
        // TODO: test hands
    }

}
