/*
 * Newrow 0.1.0
 * Blackjack
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: aaron.s.hawley@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ninthfloor.bj21.gson;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.ninthfloor.bj21.gson.RulesDealerStands;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Rules
 */
public class RulesTest {
    private final Rules model = new Rules();

    /**
     * Model tests for Rules
     */
    @Test
    public void testRules() {
        // TODO: test Rules
    }

    /**
     * Test the property 'blackjackPays'
     */
    @Test
    public void blackjackPaysTest() {
        // TODO: test blackjackPays
    }

    /**
     * Test the property 'dealerStands'
     */
    @Test
    public void dealerStandsTest() {
        // TODO: test dealerStands
    }

}
