/*
 * Blackjack
 * Blackjack
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: aaron.s.hawley@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ninthfloor.bj21.gson;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Shoe
 */
public class ShoeTest {
    private final Shoe model = new Shoe();

    /**
     * Model tests for Shoe
     */
    @Test
    public void testShoe() {
        // TODO: test Shoe
    }

    /**
     * Test the property 'tableId'
     */
    @Test
    public void tableIdTest() {
        // TODO: test tableId
    }

    /**
     * Test the property 'decks'
     */
    @Test
    public void decksTest() {
        // TODO: test decks
    }

    /**
     * Test the property 'rounds'
     */
    @Test
    public void roundsTest() {
        // TODO: test rounds
    }

    /**
     * Test the property 'discard'
     */
    @Test
    public void discardTest() {
        // TODO: test discard
    }

    /**
     * Test the property 'cut'
     */
    @Test
    public void cutTest() {
        // TODO: test cut
    }

}
