/*
 * Blackjack
 * Blackjack
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: aaron.s.hawley@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ninthfloor.bj21.gson;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Table
 */
public class TableTest {
    private final Table model = new Table();

    /**
     * Model tests for Table
     */
    @Test
    public void testTable() {
        // TODO: test Table
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'decks'
     */
    @Test
    public void decksTest() {
        // TODO: test decks
    }

    /**
     * Test the property 'seats'
     */
    @Test
    public void seatsTest() {
        // TODO: test seats
    }

    /**
     * Test the property 'players'
     */
    @Test
    public void playersTest() {
        // TODO: test players
    }

    /**
     * Test the property 'minimum'
     */
    @Test
    public void minimumTest() {
        // TODO: test minimum
    }

    /**
     * Test the property 'maximum'
     */
    @Test
    public void maximumTest() {
        // TODO: test maximum
    }

    /**
     * Test the property 'rounds'
     */
    @Test
    public void roundsTest() {
        // TODO: test rounds
    }

}
