/*
 * Blackjack
 * Blackjack
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: aaron.s.hawley@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ninthfloor.bj21.gson;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets Faces
 */
@JsonAdapter(Faces.Adapter.class)
public enum Faces {
  
  A("A"),
  
  K("K"),
  
  Q("Q"),
  
  J("J"),
  
  _10("10"),
  
  _9("9"),
  
  _8("8"),
  
  _7("7"),
  
  _6("6"),
  
  _5("5"),
  
  _4("4"),
  
  _3("3"),
  
  _2("2");

  private String value;

  Faces(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Faces fromValue(String value) {
    for (Faces b : Faces.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<Faces> {
    @Override
    public void write(final JsonWriter jsonWriter, final Faces enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Faces read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Faces.fromValue(value);
    }
  }
}

