/*
 * Blackjack
 * Blackjack
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: aaron.s.hawley@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ninthfloor.bj21.gson;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Hands
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-05-19T09:07:39.626-04:00[America/New_York]")
public class Hands {
  public static final String SERIALIZED_NAME_SEAT_ID = "seatId";
  @SerializedName(SERIALIZED_NAME_SEAT_ID)
  private Long seatId;

  public static final String SERIALIZED_NAME_BET = "bet";
  @SerializedName(SERIALIZED_NAME_BET)
  private Long bet;

  public static final String SERIALIZED_NAME_HANDS = "hands";
  @SerializedName(SERIALIZED_NAME_HANDS)
  private List<Long> hands = new ArrayList<>();


  public Hands seatId(Long seatId) {
    
    this.seatId = seatId;
    return this;
  }

   /**
   * Player number
   * @return seatId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Player number")

  public Long getSeatId() {
    return seatId;
  }


  public void setSeatId(Long seatId) {
    this.seatId = seatId;
  }


  public Hands bet(Long bet) {
    
    this.bet = bet;
    return this;
  }

   /**
   * Initial player bet
   * @return bet
  **/
  @ApiModelProperty(required = true, value = "Initial player bet")

  public Long getBet() {
    return bet;
  }


  public void setBet(Long bet) {
    this.bet = bet;
  }


  public Hands hands(List<Long> hands) {
    
    this.hands = hands;
    return this;
  }

  public Hands addHandsItem(Long handsItem) {
    this.hands.add(handsItem);
    return this;
  }

   /**
   * Hand numbers
   * @return hands
  **/
  @ApiModelProperty(required = true, value = "Hand numbers")

  public List<Long> getHands() {
    return hands;
  }


  public void setHands(List<Long> hands) {
    this.hands = hands;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Hands hands = (Hands) o;
    return Objects.equals(this.seatId, hands.seatId) &&
        Objects.equals(this.bet, hands.bet) &&
        Objects.equals(this.hands, hands.hands);
  }

  @Override
  public int hashCode() {
    return Objects.hash(seatId, bet, hands);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Hands {\n");
    sb.append("    seatId: ").append(toIndentedString(seatId)).append("\n");
    sb.append("    bet: ").append(toIndentedString(bet)).append("\n");
    sb.append("    hands: ").append(toIndentedString(hands)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

