/*
 * Newrow 0.1.0
 * Blackjack
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: aaron.s.hawley@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ninthfloor.bj21.gson;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets Pays
 */
@JsonAdapter(Pays.Adapter.class)
public enum Pays {
  
  _3_TO_2("3 to 2"),
  
  _6_TO_5("6 to 5");

  private String value;

  Pays(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Pays fromValue(String value) {
    for (Pays b : Pays.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<Pays> {
    @Override
    public void write(final JsonWriter jsonWriter, final Pays enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Pays read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Pays.fromValue(value);
    }
  }
}

