/*
 * Blackjack
 * Blackjack
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: aaron.s.hawley@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ninthfloor.bj21.gson;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.ninthfloor.bj21.gson.Hands;

/**
 * Player
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-05-19T09:07:39.626-04:00[America/New_York]")
public class Player {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_CHIPS = "chips";
  @SerializedName(SERIALIZED_NAME_CHIPS)
  private Long chips;

  public static final String SERIALIZED_NAME_HAND = "hand";
  @SerializedName(SERIALIZED_NAME_HAND)
  private Hands hand;


  public Player id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Player number
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Player number")

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public Player chips(Long chips) {
    
    this.chips = chips;
    return this;
  }

   /**
   * Player chip total
   * @return chips
  **/
  @ApiModelProperty(required = true, value = "Player chip total")

  public Long getChips() {
    return chips;
  }


  public void setChips(Long chips) {
    this.chips = chips;
  }


  public Player hand(Hands hand) {
    
    this.hand = hand;
    return this;
  }

   /**
   * Get hand
   * @return hand
  **/
  @ApiModelProperty(required = true, value = "")

  public Hands getHand() {
    return hand;
  }


  public void setHand(Hands hand) {
    this.hand = hand;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Player player = (Player) o;
    return Objects.equals(this.id, player.id) &&
        Objects.equals(this.chips, player.chips) &&
        Objects.equals(this.hand, player.hand);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, chips, hand);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Player {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    chips: ").append(toIndentedString(chips)).append("\n");
    sb.append("    hand: ").append(toIndentedString(hand)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

