/*
 * Newrow 0.1.0
 * Blackjack
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: aaron.s.hawley@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ninthfloor.bj21.api.gson;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Card
 */
public class CardTest {
    private final Card model = new Card();

    /**
     * Model tests for Card
     */
    @Test
    public void testCard() {
        // TODO: test Card
    }

    /**
     * Test the property 'suit'
     */
    @Test
    public void suitTest() {
        // TODO: test suit
    }

    /**
     * Test the property 'face'
     */
    @Test
    public void faceTest() {
        // TODO: test face
    }

}
