/*
 * Newrow 1.3.1
 * Newrow API
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: help@newrow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.ninthfloor.bj21.api.gson;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UserDeletedData
 */
public class UserDeletedDataTest {
    private final UserDeletedData model = new UserDeletedData();

    /**
     * Model tests for UserDeletedData
     */
    @Test
    public void testUserDeletedData() {
        // TODO: test UserDeletedData
    }

    /**
     * Test the property 'deletedUserRooms'
     */
    @Test
    public void deletedUserRoomsTest() {
        // TODO: test deletedUserRooms
    }

    /**
     * Test the property 'companyUserDeleted'
     */
    @Test
    public void companyUserDeletedTest() {
        // TODO: test companyUserDeleted
    }

}
